### PR TITLE
[schedy] Fix AppDaemon 4.0.0 bug re: incorrect callback signature

### PR DESCRIPTION
**Pull request by bachya**
Fixes https://github.com/efficiosoft/hass-apps/issues/36.

AppDaemon 4.0.0 appears to be stricter about callback signatures; this PR fixes one spot (re-evaluation of schedules) where I found this to occur.

### CODE REVIEW

**Comment by efficiosoft** [comment]
Hi,

Thanks for the PR. I already discussed this "feature" with the AppDaemon devs some months ago and was still hoping they'd drop it again in the final release, but I seem to be in bad luck.

**Comment by efficiosoft** [comment]
BTW, this won't even work, because there is no `self` on a function which is no bound method. I'll end up adding a lot of wrappers around callback handlers for nothing.

**Comment by efficiosoft** [comment]
Just for reference: https://github.com/home-assistant/appdaemon/issues/462

**Comment by bachya** [comment]
Thanks for the clarification!

**Pull request closed without merging**
