### PR TITLE
Added info about app_name

### PR DESCRIPTION
**Pull request by ooii**
Added a comment in front of the app_name to explain the purpose of this parameter.

### CODE REVIEW

**Comment by efficiosoft** [comment]
Thanks for the PR. However, exactly that is described in the Events chapter where all the events are introduced.

**Comment by ooii** [comment]
I agree but, from my experience, repeating the information is not harmful.

**Comment by efficiosoft** [comment]
Right, I'll add it to the sample config as well. Thanks.

**Comment by efficiosoft** [comment]
Committed.

**Pull request closed without merging**
